#! /usr/bin/env python

from website import app, db
from website.auth.auth_models import User  
from website.home.home_models import SensorData
from website.home_sk.home_models import SHSKSensorData
from flask_script import Manager, prompt_bool
from flask_migrate import Migrate, MigrateCommand
from datetime import datetime

manager = Manager(app)
migrate = Migrate(app, db)

manager.add_command('db', MigrateCommand)

@manager.command
def insert_data():
    db.create_all()
    db.session.add(User(username='hongjin', email='skyryuhhj@gmail.com', password='test'))
    db.session.add(User(username='skyryu', email='skyryu@126.com', password='test'))
    db.session.commit()
    print('Initalized the database')

@manager.command
def dropdb():
    if prompt_bool('Are you sure you want to lose all your data'):
        db.drop_all()
        print('Dropped the database')

@manager.command
def testDB_Ajax():
    import time
    i = 0
    while i<10000:
        db.session.add(SensorData(sensor_name='hydrolevel1901', component_name='R1', data_type='all', 
                                  value=12.3, time_stamp=datetime.strptime(
                                    datetime.utcnow().strftime('%Y%m%d %H:%M:%S'), '%Y%m%d %H:%M:%S')
        )) 
        db.session.add(SensorData(sensor_name='hydrolevel1902', component_name='R1', data_type='all',
                                  value=12.3, time_stamp=datetime.strptime(
                                    datetime.utcnow().strftime('%Y%m%d %H:%M:%S'), '%Y%m%d %H:%M:%S')
        ))
        db.session.add(SensorData(sensor_name='hydrolevel1903', component_name='R1', data_type='all',
                                  value=12.3, time_stamp=datetime.strptime(
                                    datetime.utcnow().strftime('%Y%m%d %H:%M:%S'), '%Y%m%d %H:%M:%S')
        ))
        db.session.commit()
        time.sleep(1)
        print('time:{0}'.format(i))
        i+=1 

@manager.command
def db_insertSensorData():
    #F1
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='218.5',   time_stamp=datetime.strptime('20181228 00:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='208',     time_stamp=datetime.strptime('20181228 00:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='97.25',   time_stamp=datetime.strptime('20181228 01:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='119.25',  time_stamp=datetime.strptime('20181228 01:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='131.5',   time_stamp=datetime.strptime('20181228 02:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='75.5',    time_stamp=datetime.strptime('20181228 02:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='83.5',    time_stamp=datetime.strptime('20181228 03:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='226.75',  time_stamp=datetime.strptime('20181228 03:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='122.25',  time_stamp=datetime.strptime('20181228 04:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='182',     time_stamp=datetime.strptime('20181228 04:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='140',     time_stamp=datetime.strptime('20181228 05:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='206.75',  time_stamp=datetime.strptime('20181228 05:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='217',     time_stamp=datetime.strptime('20181228 06:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='136',     time_stamp=datetime.strptime('20181228 06:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='118.25',  time_stamp=datetime.strptime('20181228 07:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='181',     time_stamp=datetime.strptime('20181228 07:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='164.75',  time_stamp=datetime.strptime('20181228 08:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='217.25',  time_stamp=datetime.strptime('20181228 08:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='115.75',  time_stamp=datetime.strptime('20181228 09:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='146.5',   time_stamp=datetime.strptime('20181228 09:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='88.25',   time_stamp=datetime.strptime('20181228 10:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='123.25',  time_stamp=datetime.strptime('20181228 10:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='147.75',  time_stamp=datetime.strptime('20181228 11:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='84.5',    time_stamp=datetime.strptime('20181228 11:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='172',     time_stamp=datetime.strptime('20181228 12:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='180',     time_stamp=datetime.strptime('20181228 12:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='171',     time_stamp=datetime.strptime('20181228 13:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='191.5',   time_stamp=datetime.strptime('20181228 13:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='173.75',  time_stamp=datetime.strptime('20181228 14:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='121.25',  time_stamp=datetime.strptime('20181228 14:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='131.5',   time_stamp=datetime.strptime('20181228 15:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='103.5',   time_stamp=datetime.strptime('20181228 15:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='131.5',   time_stamp=datetime.strptime('20181228 16:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='133.75',  time_stamp=datetime.strptime('20181228 16:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='178.25',  time_stamp=datetime.strptime('20181228 17:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='105',     time_stamp=datetime.strptime('20181228 17:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='187.25',  time_stamp=datetime.strptime('20181228 18:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='166.5',   time_stamp=datetime.strptime('20181228 18:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='158.75',  time_stamp=datetime.strptime('20181228 19:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='156.5',   time_stamp=datetime.strptime('20181228 19:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='120',     time_stamp=datetime.strptime('20181228 20:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='119.75',  time_stamp=datetime.strptime('20181228 20:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='152',     time_stamp=datetime.strptime('20181228 21:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='193.75',  time_stamp=datetime.strptime('20181228 21:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='97.5',    time_stamp=datetime.strptime('20181228 22:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='148.75',  time_stamp=datetime.strptime('20181228 22:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='146.5',   time_stamp=datetime.strptime('20181228 23:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='201.75',  time_stamp=datetime.strptime('20181228 23:30:00', '%Y%m%d %H:%M:%S')))
    #F2
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='211.25',  time_stamp=datetime.strptime('20181228 00:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='166.25',  time_stamp=datetime.strptime('20181228 00:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='81.25',   time_stamp=datetime.strptime('20181228 01:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='102.5',   time_stamp=datetime.strptime('20181228 01:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='142.25',  time_stamp=datetime.strptime('20181228 02:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='103',     time_stamp=datetime.strptime('20181228 02:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='172.25',  time_stamp=datetime.strptime('20181228 03:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='181.5',   time_stamp=datetime.strptime('20181228 03:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='197.5',   time_stamp=datetime.strptime('20181228 04:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='176.5',   time_stamp=datetime.strptime('20181228 04:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='176.75',  time_stamp=datetime.strptime('20181228 05:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='148',     time_stamp=datetime.strptime('20181228 05:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='203.75',  time_stamp=datetime.strptime('20181228 06:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='174.25',  time_stamp=datetime.strptime('20181228 06:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='113.25',  time_stamp=datetime.strptime('20181228 07:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='88.25',   time_stamp=datetime.strptime('20181228 07:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='80',  time_stamp=datetime.strptime('20181228 08:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='156.25',  time_stamp=datetime.strptime('20181228 08:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='125.75',  time_stamp=datetime.strptime('20181228 09:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='104',     time_stamp=datetime.strptime('20181228 09:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='166',     time_stamp=datetime.strptime('20181228 10:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='146.25',  time_stamp=datetime.strptime('20181228 10:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='228.25',  time_stamp=datetime.strptime('20181228 11:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='81',  time_stamp=datetime.strptime('20181228 11:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='158.5',   time_stamp=datetime.strptime('20181228 12:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='88.75',   time_stamp=datetime.strptime('20181228 12:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='116.25',  time_stamp=datetime.strptime('20181228 13:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='92.25',   time_stamp=datetime.strptime('20181228 13:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='161',     time_stamp=datetime.strptime('20181228 14:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='181',     time_stamp=datetime.strptime('20181228 14:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='98.75',   time_stamp=datetime.strptime('20181228 15:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='164',     time_stamp=datetime.strptime('20181228 15:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='112.75',  time_stamp=datetime.strptime('20181228 16:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='225.25',  time_stamp=datetime.strptime('20181228 16:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='88.25',   time_stamp=datetime.strptime('20181228 17:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='104',     time_stamp=datetime.strptime('20181228 17:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='209',     time_stamp=datetime.strptime('20181228 18:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='96.25',   time_stamp=datetime.strptime('20181228 18:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='196.25',  time_stamp=datetime.strptime('20181228 19:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='78.5',    time_stamp=datetime.strptime('20181228 19:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='106.75',  time_stamp=datetime.strptime('20181228 20:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='220.5',   time_stamp=datetime.strptime('20181228 20:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='205',     time_stamp=datetime.strptime('20181228 21:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='78',  time_stamp=datetime.strptime('20181228 21:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='144.25',  time_stamp=datetime.strptime('20181228 22:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='95.25',   time_stamp=datetime.strptime('20181228 22:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='134.5',   time_stamp=datetime.strptime('20181228 23:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='99.5',    time_stamp=datetime.strptime('20181228 23:30:00', '%Y%m%d %H:%M:%S')))
    #F3
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='89.25',   time_stamp=datetime.strptime('20181228 00:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='153.25',  time_stamp=datetime.strptime('20181228 00:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='140.75',  time_stamp=datetime.strptime('20181228 01:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='166',     time_stamp=datetime.strptime('20181228 01:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='127',     time_stamp=datetime.strptime('20181228 02:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='122.5',   time_stamp=datetime.strptime('20181228 02:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='197.25',  time_stamp=datetime.strptime('20181228 03:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='104.25',  time_stamp=datetime.strptime('20181228 03:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='111.5',   time_stamp=datetime.strptime('20181228 04:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='159.25',  time_stamp=datetime.strptime('20181228 04:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='113.5',   time_stamp=datetime.strptime('20181228 05:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='100.25',  time_stamp=datetime.strptime('20181228 05:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='218.25',  time_stamp=datetime.strptime('20181228 06:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='120.75',  time_stamp=datetime.strptime('20181228 06:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='99',  time_stamp=datetime.strptime('20181228 07:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='128.5',   time_stamp=datetime.strptime('20181228 07:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='227.75',  time_stamp=datetime.strptime('20181228 08:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='127.5',   time_stamp=datetime.strptime('20181228 08:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='135.5',   time_stamp=datetime.strptime('20181228 09:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='146.75',  time_stamp=datetime.strptime('20181228 09:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='194',     time_stamp=datetime.strptime('20181228 10:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='219.75',  time_stamp=datetime.strptime('20181228 10:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='170.25',  time_stamp=datetime.strptime('20181228 11:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='160.75',  time_stamp=datetime.strptime('20181228 11:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='225.5',   time_stamp=datetime.strptime('20181228 12:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='182',     time_stamp=datetime.strptime('20181228 12:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='221.5',   time_stamp=datetime.strptime('20181228 13:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='96.25',   time_stamp=datetime.strptime('20181228 13:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='85.25',   time_stamp=datetime.strptime('20181228 14:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='186.25',  time_stamp=datetime.strptime('20181228 14:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='153.25',  time_stamp=datetime.strptime('20181228 15:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='129.25',  time_stamp=datetime.strptime('20181228 15:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='141.75',  time_stamp=datetime.strptime('20181228 16:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='130',     time_stamp=datetime.strptime('20181228 16:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='224',     time_stamp=datetime.strptime('20181228 17:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='126.5',   time_stamp=datetime.strptime('20181228 17:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='160',     time_stamp=datetime.strptime('20181228 18:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='158.25',  time_stamp=datetime.strptime('20181228 18:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='139',     time_stamp=datetime.strptime('20181228 19:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='225.25',  time_stamp=datetime.strptime('20181228 19:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='194.5',   time_stamp=datetime.strptime('20181228 20:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='180',     time_stamp=datetime.strptime('20181228 20:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='106.5',   time_stamp=datetime.strptime('20181228 21:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='102.5',   time_stamp=datetime.strptime('20181228 21:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='97.75',   time_stamp=datetime.strptime('20181228 22:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='100.75',  time_stamp=datetime.strptime('20181228 22:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='141',     time_stamp=datetime.strptime('20181228 23:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='213.25',  time_stamp=datetime.strptime('20181228 23:30:00', '%Y%m%d %H:%M:%S')))
    #F4
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='464.75',  time_stamp=datetime.strptime('20181228 00:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='391.25',  time_stamp=datetime.strptime('20181228 00:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='405.5',   time_stamp=datetime.strptime('20181228 01:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='256',     time_stamp=datetime.strptime('20181228 01:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='363.5',   time_stamp=datetime.strptime('20181228 02:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='423.25',  time_stamp=datetime.strptime('20181228 02:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='360',     time_stamp=datetime.strptime('20181228 03:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='399',     time_stamp=datetime.strptime('20181228 03:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='415.75',  time_stamp=datetime.strptime('20181228 04:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='470.25',  time_stamp=datetime.strptime('20181228 04:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='282.25',  time_stamp=datetime.strptime('20181228 05:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='357.75',  time_stamp=datetime.strptime('20181228 05:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='300.75',  time_stamp=datetime.strptime('20181228 06:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='312.25',  time_stamp=datetime.strptime('20181228 06:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='405.5',   time_stamp=datetime.strptime('20181228 07:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='407.5',   time_stamp=datetime.strptime('20181228 07:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='464.25',  time_stamp=datetime.strptime('20181228 08:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='363',     time_stamp=datetime.strptime('20181228 08:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='429.25',  time_stamp=datetime.strptime('20181228 09:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='321',     time_stamp=datetime.strptime('20181228 09:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='479.25',  time_stamp=datetime.strptime('20181228 10:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='277.5',   time_stamp=datetime.strptime('20181228 10:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='337.5',   time_stamp=datetime.strptime('20181228 11:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='407.5',   time_stamp=datetime.strptime('20181228 11:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='460.5',   time_stamp=datetime.strptime('20181228 12:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='443.5',   time_stamp=datetime.strptime('20181228 12:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='343.5',   time_stamp=datetime.strptime('20181228 13:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='364.25',  time_stamp=datetime.strptime('20181228 13:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='367.5',   time_stamp=datetime.strptime('20181228 14:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='474.25',  time_stamp=datetime.strptime('20181228 14:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='471.25',  time_stamp=datetime.strptime('20181228 15:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='498.25',  time_stamp=datetime.strptime('20181228 15:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='311.5',   time_stamp=datetime.strptime('20181228 16:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='406',     time_stamp=datetime.strptime('20181228 16:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='367',     time_stamp=datetime.strptime('20181228 17:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='463.5',   time_stamp=datetime.strptime('20181228 17:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='310.75',  time_stamp=datetime.strptime('20181228 18:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='243.75',  time_stamp=datetime.strptime('20181228 18:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='384',     time_stamp=datetime.strptime('20181228 19:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='383.5',   time_stamp=datetime.strptime('20181228 19:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='269.5',   time_stamp=datetime.strptime('20181228 20:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='306.25',  time_stamp=datetime.strptime('20181228 20:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='236.25',  time_stamp=datetime.strptime('20181228 21:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='476',     time_stamp=datetime.strptime('20181228 21:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='374.25',  time_stamp=datetime.strptime('20181228 22:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='418',     time_stamp=datetime.strptime('20181228 22:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='359.75',  time_stamp=datetime.strptime('20181228 23:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='394.25',  time_stamp=datetime.strptime('20181228 23:30:00', '%Y%m%d %H:%M:%S')))
    
    db.session.commit()


if __name__ == '__main__':
    manager.run()