#! /usr/bin/env python

from website import app, db
from website.auth.auth_models import User  
from website.home.home_models import SensorData
from website.home_sk.home_models import SHSKSensorData
from website.main.main_models import CheckTable

from flask_script import Manager, prompt_bool
from flask_migrate import Migrate, MigrateCommand
from datetime import datetime

manager = Manager(app)
migrate = Migrate(app, db)

manager.add_command('db', MigrateCommand)

@manager.command
def insert_data():
    db.create_all()
    db.session.add(User(username='hongjin', email='skyryuhhj@gmail.com', password='test'))
    db.session.add(User(username='skyryu', email='skyryu@126.com', password='test'))
    db.session.commit()
    print('Initalized the database')

@manager.command
def dropdb():
    if prompt_bool('Are you sure you want to lose all your data'):
        db.drop_all()
        print('Dropped the database')

@manager.command
def testDB_Ajax():
    import time
    i = 0
    while i<10000:
        db.session.add(SensorData(sensor_name='hydrolevel1901', component_name='R1', data_type='all', 
                                  value=12.3, time_stamp=datetime.strptime(
                                    datetime.utcnow().strftime('%Y%m%d %H:%M:%S'), '%Y%m%d %H:%M:%S')
        )) 
        db.session.add(SensorData(sensor_name='hydrolevel1902', component_name='R1', data_type='all',
                                  value=12.3, time_stamp=datetime.strptime(
                                    datetime.utcnow().strftime('%Y%m%d %H:%M:%S'), '%Y%m%d %H:%M:%S')
        ))
        db.session.add(SensorData(sensor_name='hydrolevel1903', component_name='R1', data_type='all',
                                  value=12.3, time_stamp=datetime.strptime(
                                    datetime.utcnow().strftime('%Y%m%d %H:%M:%S'), '%Y%m%d %H:%M:%S')
        ))
        db.session.commit()
        time.sleep(1)
        print('time:{0}'.format(i))
        i+=1 

@manager.command
def db_insertSensorData():
    #F1
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='18.25',  time_stamp=datetime.strptime('20181228 00:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='26.75',  time_stamp=datetime.strptime('20181228 00:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='18.25',  time_stamp=datetime.strptime('20181228 01:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='31.75',  time_stamp=datetime.strptime('20181228 01:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='25.25',  time_stamp=datetime.strptime('20181228 02:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='29', time_stamp=datetime.strptime('20181228 02:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='11', time_stamp=datetime.strptime('20181228 03:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='16.75',  time_stamp=datetime.strptime('20181228 03:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='19.5',   time_stamp=datetime.strptime('20181228 04:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='10.25',  time_stamp=datetime.strptime('20181228 04:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='15.5',   time_stamp=datetime.strptime('20181228 05:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='19', time_stamp=datetime.strptime('20181228 05:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='9.75',   time_stamp=datetime.strptime('20181228 06:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='14.25',  time_stamp=datetime.strptime('20181228 06:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='29.75',  time_stamp=datetime.strptime('20181228 07:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='26.75',  time_stamp=datetime.strptime('20181228 07:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='30.25',  time_stamp=datetime.strptime('20181228 08:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='29.25',  time_stamp=datetime.strptime('20181228 08:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='30', time_stamp=datetime.strptime('20181228 09:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='24.75',  time_stamp=datetime.strptime('20181228 09:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='25.75',  time_stamp=datetime.strptime('20181228 10:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='28', time_stamp=datetime.strptime('20181228 10:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='8.5',    time_stamp=datetime.strptime('20181228 11:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='14.75',  time_stamp=datetime.strptime('20181228 11:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='17.25',  time_stamp=datetime.strptime('20181228 12:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='30', time_stamp=datetime.strptime('20181228 12:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='33.5',   time_stamp=datetime.strptime('20181228 13:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='21.75',  time_stamp=datetime.strptime('20181228 13:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='28.25',  time_stamp=datetime.strptime('20181228 14:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='9.25',   time_stamp=datetime.strptime('20181228 14:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='12.5',   time_stamp=datetime.strptime('20181228 15:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='13', time_stamp=datetime.strptime('20181228 15:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='11', time_stamp=datetime.strptime('20181228 16:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='19.5',   time_stamp=datetime.strptime('20181228 16:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='12.25',  time_stamp=datetime.strptime('20181228 17:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='18', time_stamp=datetime.strptime('20181228 17:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='28.5',   time_stamp=datetime.strptime('20181228 18:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='32', time_stamp=datetime.strptime('20181228 18:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='20.25',  time_stamp=datetime.strptime('20181228 19:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='33.75',  time_stamp=datetime.strptime('20181228 19:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='19.25',  time_stamp=datetime.strptime('20181228 20:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='12.75',  time_stamp=datetime.strptime('20181228 20:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='18.75',  time_stamp=datetime.strptime('20181228 21:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='19.75',  time_stamp=datetime.strptime('20181228 21:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='29', time_stamp=datetime.strptime('20181228 22:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='29.75',  time_stamp=datetime.strptime('20181228 22:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='29.75',  time_stamp=datetime.strptime('20181228 23:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre1', component_name='default', data_type='all', value='9.5',    time_stamp=datetime.strptime('20181228 23:30:00', '%Y%m%d %H:%M:%S')))
    #F2
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='29.75',  time_stamp=datetime.strptime('20181228 00:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='14', time_stamp=datetime.strptime('20181228 00:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='23.75',  time_stamp=datetime.strptime('20181228 01:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='32.25',  time_stamp=datetime.strptime('20181228 01:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='27.5',   time_stamp=datetime.strptime('20181228 02:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='10', time_stamp=datetime.strptime('20181228 02:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='21', time_stamp=datetime.strptime('20181228 03:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='10.75',  time_stamp=datetime.strptime('20181228 03:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='15.5',   time_stamp=datetime.strptime('20181228 04:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='11.75',  time_stamp=datetime.strptime('20181228 04:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='17', time_stamp=datetime.strptime('20181228 05:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='30.75',  time_stamp=datetime.strptime('20181228 05:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='30', time_stamp=datetime.strptime('20181228 06:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='13.5',   time_stamp=datetime.strptime('20181228 06:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='24.5',   time_stamp=datetime.strptime('20181228 07:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='13.5',   time_stamp=datetime.strptime('20181228 07:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='24.5',   time_stamp=datetime.strptime('20181228 08:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='11.75',  time_stamp=datetime.strptime('20181228 08:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='12.25',  time_stamp=datetime.strptime('20181228 09:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='11.25',  time_stamp=datetime.strptime('20181228 09:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='17', time_stamp=datetime.strptime('20181228 10:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='14.75',  time_stamp=datetime.strptime('20181228 10:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='22.25',  time_stamp=datetime.strptime('20181228 11:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='31.5',   time_stamp=datetime.strptime('20181228 11:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='22.75',  time_stamp=datetime.strptime('20181228 12:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='26.75',  time_stamp=datetime.strptime('20181228 12:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='21.5',   time_stamp=datetime.strptime('20181228 13:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='16.25',  time_stamp=datetime.strptime('20181228 13:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='24.5',   time_stamp=datetime.strptime('20181228 14:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='8',  time_stamp=datetime.strptime('20181228 14:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='20.5',   time_stamp=datetime.strptime('20181228 15:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='31', time_stamp=datetime.strptime('20181228 15:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='13', time_stamp=datetime.strptime('20181228 16:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='24.5',   time_stamp=datetime.strptime('20181228 16:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='10.75',  time_stamp=datetime.strptime('20181228 17:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='18.25',  time_stamp=datetime.strptime('20181228 17:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='14.25',  time_stamp=datetime.strptime('20181228 18:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='32.75',  time_stamp=datetime.strptime('20181228 18:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='25.5',   time_stamp=datetime.strptime('20181228 19:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='27.25',  time_stamp=datetime.strptime('20181228 19:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='10.25',  time_stamp=datetime.strptime('20181228 20:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='24.25',  time_stamp=datetime.strptime('20181228 20:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='8.5',    time_stamp=datetime.strptime('20181228 21:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='20.5',   time_stamp=datetime.strptime('20181228 21:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='22.25',  time_stamp=datetime.strptime('20181228 22:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='32.5',   time_stamp=datetime.strptime('20181228 22:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='10.5',   time_stamp=datetime.strptime('20181228 23:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre2', component_name='default', data_type='all', value='26.5',   time_stamp=datetime.strptime('20181228 23:30:00', '%Y%m%d %H:%M:%S')))
    #F3
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='18.75',  time_stamp=datetime.strptime('20181228 00:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='9.25',   time_stamp=datetime.strptime('20181228 00:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='19.5',   time_stamp=datetime.strptime('20181228 01:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='22.75',  time_stamp=datetime.strptime('20181228 01:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='14', time_stamp=datetime.strptime('20181228 02:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='26', time_stamp=datetime.strptime('20181228 02:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='31.75',  time_stamp=datetime.strptime('20181228 03:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='12.75',  time_stamp=datetime.strptime('20181228 03:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='11.75',  time_stamp=datetime.strptime('20181228 04:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='10.5',   time_stamp=datetime.strptime('20181228 04:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='20.75',  time_stamp=datetime.strptime('20181228 05:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='30.75',  time_stamp=datetime.strptime('20181228 05:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='12.75',  time_stamp=datetime.strptime('20181228 06:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='21.5',   time_stamp=datetime.strptime('20181228 06:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='14.75',  time_stamp=datetime.strptime('20181228 07:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='27', time_stamp=datetime.strptime('20181228 07:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='25.75',  time_stamp=datetime.strptime('20181228 08:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='28.75',  time_stamp=datetime.strptime('20181228 08:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='15.75',  time_stamp=datetime.strptime('20181228 09:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='30.25',  time_stamp=datetime.strptime('20181228 09:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='25', time_stamp=datetime.strptime('20181228 10:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='34', time_stamp=datetime.strptime('20181228 10:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='33.75',  time_stamp=datetime.strptime('20181228 11:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='31.75',  time_stamp=datetime.strptime('20181228 11:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='33.25',  time_stamp=datetime.strptime('20181228 12:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='13', time_stamp=datetime.strptime('20181228 12:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='31', time_stamp=datetime.strptime('20181228 13:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='15', time_stamp=datetime.strptime('20181228 13:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='30', time_stamp=datetime.strptime('20181228 14:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='29', time_stamp=datetime.strptime('20181228 14:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='29', time_stamp=datetime.strptime('20181228 15:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='26', time_stamp=datetime.strptime('20181228 15:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='25.5',   time_stamp=datetime.strptime('20181228 16:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='29.5',   time_stamp=datetime.strptime('20181228 16:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='20.5',   time_stamp=datetime.strptime('20181228 17:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='30.25',  time_stamp=datetime.strptime('20181228 17:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='15.25',  time_stamp=datetime.strptime('20181228 18:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='13.75',  time_stamp=datetime.strptime('20181228 18:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='18.75',  time_stamp=datetime.strptime('20181228 19:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='13.5',   time_stamp=datetime.strptime('20181228 19:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='15.75',  time_stamp=datetime.strptime('20181228 20:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='28.5',   time_stamp=datetime.strptime('20181228 20:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='13.75',  time_stamp=datetime.strptime('20181228 21:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='20.5',   time_stamp=datetime.strptime('20181228 21:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='27.25',  time_stamp=datetime.strptime('20181228 22:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='14', time_stamp=datetime.strptime('20181228 22:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='32.25',  time_stamp=datetime.strptime('20181228 23:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre3', component_name='default', data_type='all', value='33.25',  time_stamp=datetime.strptime('20181228 23:30:00', '%Y%m%d %H:%M:%S')))
    #F4
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='39.75',  time_stamp=datetime.strptime('20181228 00:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='53.25',  time_stamp=datetime.strptime('20181228 00:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='71.75',  time_stamp=datetime.strptime('20181228 01:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='45.5',   time_stamp=datetime.strptime('20181228 01:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='39', time_stamp=datetime.strptime('20181228 02:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='33.75',  time_stamp=datetime.strptime('20181228 02:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='41.25',  time_stamp=datetime.strptime('20181228 03:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='36.5',   time_stamp=datetime.strptime('20181228 03:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='66.5',   time_stamp=datetime.strptime('20181228 04:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='65.25',  time_stamp=datetime.strptime('20181228 04:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='36.5',   time_stamp=datetime.strptime('20181228 05:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='61', time_stamp=datetime.strptime('20181228 05:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='60.25',  time_stamp=datetime.strptime('20181228 06:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='47.5',   time_stamp=datetime.strptime('20181228 06:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='44.75',  time_stamp=datetime.strptime('20181228 07:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='57.5',   time_stamp=datetime.strptime('20181228 07:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='59.5',   time_stamp=datetime.strptime('20181228 08:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='48.5',   time_stamp=datetime.strptime('20181228 08:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='52.5',   time_stamp=datetime.strptime('20181228 09:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='50.25',  time_stamp=datetime.strptime('20181228 09:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='50.5',   time_stamp=datetime.strptime('20181228 10:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='30.25',  time_stamp=datetime.strptime('20181228 10:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='37.5',   time_stamp=datetime.strptime('20181228 11:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='38.5',   time_stamp=datetime.strptime('20181228 11:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='45.5',   time_stamp=datetime.strptime('20181228 12:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='66', time_stamp=datetime.strptime('20181228 12:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='48.25',  time_stamp=datetime.strptime('20181228 13:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='33.5',   time_stamp=datetime.strptime('20181228 13:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='61.25',  time_stamp=datetime.strptime('20181228 14:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='43.5',   time_stamp=datetime.strptime('20181228 14:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='63.75',  time_stamp=datetime.strptime('20181228 15:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='52.5',   time_stamp=datetime.strptime('20181228 15:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='49.25',  time_stamp=datetime.strptime('20181228 16:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='71', time_stamp=datetime.strptime('20181228 16:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='70', time_stamp=datetime.strptime('20181228 17:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='35.25',  time_stamp=datetime.strptime('20181228 17:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='73', time_stamp=datetime.strptime('20181228 18:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='67', time_stamp=datetime.strptime('20181228 18:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='39.5',   time_stamp=datetime.strptime('20181228 19:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='46.5',   time_stamp=datetime.strptime('20181228 19:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='52.25',  time_stamp=datetime.strptime('20181228 20:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='72.75',  time_stamp=datetime.strptime('20181228 20:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='38.75',  time_stamp=datetime.strptime('20181228 21:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='43.5',   time_stamp=datetime.strptime('20181228 21:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='53.25',  time_stamp=datetime.strptime('20181228 22:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='54', time_stamp=datetime.strptime('20181228 22:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='32.5',   time_stamp=datetime.strptime('20181228 23:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SensorData(sensor_name='winpre4', component_name='default', data_type='all', value='34.25',  time_stamp=datetime.strptime('20181228 23:30:00', '%Y%m%d %H:%M:%S')))


    db.session.add(SHSKSensorData(sensor_name='winpre1', component_name='default', data_type='all', value='18.25',  time_stamp=datetime.strptime('20190108 14:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre1', component_name='default', data_type='all', value='26.75',  time_stamp=datetime.strptime('20190108 14:15:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre1', component_name='default', data_type='all', value='12.75',  time_stamp=datetime.strptime('20190108 14:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre1', component_name='default', data_type='all', value='29.5',   time_stamp=datetime.strptime('20190108 14:45:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre1', component_name='default', data_type='all', value='7.25',   time_stamp=datetime.strptime('20190108 15:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre1', component_name='default', data_type='all', value='5.25',   time_stamp=datetime.strptime('20190108 15:15:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre1', component_name='default', data_type='all', value='5.25',   time_stamp=datetime.strptime('20190108 15:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre1', component_name='default', data_type='all', value='16.5',   time_stamp=datetime.strptime('20190108 15:45:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre1', component_name='default', data_type='all', value='19.5',   time_stamp=datetime.strptime('20190108 16:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre1', component_name='default', data_type='all', value='10.25',  time_stamp=datetime.strptime('20190108 16:15:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre1', component_name='default', data_type='all', value='15.5',   time_stamp=datetime.strptime('20190108 16:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre1', component_name='default', data_type='all', value='19', time_stamp=datetime.strptime('20190108 16:45:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre2', component_name='default', data_type='all', value='29.75',  time_stamp=datetime.strptime('20190108 14:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre2', component_name='default', data_type='all', value='14', time_stamp=datetime.strptime('20190108 14:15:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre2', component_name='default', data_type='all', value='33.25',  time_stamp=datetime.strptime('20190108 14:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre2', component_name='default', data_type='all', value='28', time_stamp=datetime.strptime('20190108 14:45:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre2', component_name='default', data_type='all', value='16.75',  time_stamp=datetime.strptime('20190108 15:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre2', component_name='default', data_type='all', value='17.75',  time_stamp=datetime.strptime('20190108 15:15:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre2', component_name='default', data_type='all', value='13.5',   time_stamp=datetime.strptime('20190108 15:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre2', component_name='default', data_type='all', value='7',  time_stamp=datetime.strptime('20190108 15:45:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre2', component_name='default', data_type='all', value='15.5',   time_stamp=datetime.strptime('20190108 16:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre2', component_name='default', data_type='all', value='11.75',  time_stamp=datetime.strptime('20190108 16:15:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre2', component_name='default', data_type='all', value='17', time_stamp=datetime.strptime('20190108 16:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre2', component_name='default', data_type='all', value='30.75',  time_stamp=datetime.strptime('20190108 16:45:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre3', component_name='default', data_type='all', value='18.75',  time_stamp=datetime.strptime('20190108 14:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre3', component_name='default', data_type='all', value='9.25',   time_stamp=datetime.strptime('20190108 14:15:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre3', component_name='default', data_type='all', value='15.75',  time_stamp=datetime.strptime('20190108 14:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre3', component_name='default', data_type='all', value='15.75',  time_stamp=datetime.strptime('20190108 14:45:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre3', component_name='default', data_type='all', value='15', time_stamp=datetime.strptime('20190108 15:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre3', component_name='default', data_type='all', value='9.25',   time_stamp=datetime.strptime('20190108 15:15:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre3', component_name='default', data_type='all', value='11', time_stamp=datetime.strptime('20190108 15:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre3', component_name='default', data_type='all', value='7.5',    time_stamp=datetime.strptime('20190108 15:45:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre3', component_name='default', data_type='all', value='11.75',  time_stamp=datetime.strptime('20190108 16:00:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre3', component_name='default', data_type='all', value='10.5',   time_stamp=datetime.strptime('20190108 16:15:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre3', component_name='default', data_type='all', value='20.75',  time_stamp=datetime.strptime('20190108 16:30:00', '%Y%m%d %H:%M:%S')))
    db.session.add(SHSKSensorData(sensor_name='winpre3', component_name='default', data_type='all', value='30.75',  time_stamp=datetime.strptime('20190108 16:45:00', '%Y%m%d %H:%M:%S')))

    db.session.commit()


if __name__ == '__main__':
    manager.run()