"""add CheckTable

Revision ID: 2a5eb5af0d7c
Revises: 035dc2d3c97e
Create Date: 2019-01-22 23:58:53.333313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5eb5af0d7c'
down_revision = '035dc2d3c97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=64), nullable=True),
    sa.Column('modal_name', sa.String(length=64), nullable=True),
    sa.Column('check_field', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=64), nullable=True),
    sa.Column('check_date', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proj_modal_date', 'check_table', ['project_name', 'modal_name', 'check_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proj_modal_date', table_name='check_table')
    op.drop_table('check_table')
    # ### end Alembic commands ###
