"""add SensorData table

Revision ID: 803c573329ef
Revises: 72be7d09af22
Create Date: 2018-10-20 14:44:54.233655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803c573329ef'
down_revision = '72be7d09af22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_name', sa.String(length=64), nullable=True),
    sa.Column('component_name', sa.String(length=64), nullable=True),
    sa.Column('data_type', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=64), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_component_type_time', 'sensor_data', ['sensor_name', 'component_name', 'data_type', 'time_stamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sensor_component_type_time', table_name='sensor_data')
    op.drop_table('sensor_data')
    # ### end Alembic commands ###
